-- MySQL Script generated by MySQL Workbench
-- Fri Nov 13 18:57:23 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`ZONA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ZONA` (
  `nombre_zona` VARCHAR(45) NOT NULL,
  `area` DECIMAL NULL,
  `concejal_responsable` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`nombre_zona`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`CALLE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`CALLE` (
  `nombre_calle` VARCHAR(45) NOT NULL,
  `tipo` VARCHAR(45) NULL,
  `numero_contenedores` INT NULL,
  `zona` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`nombre_calle`),
  UNIQUE INDEX `nombre_calle_UNIQUE` (`nombre_calle` ASC) VISIBLE,
  INDEX `Zona_idx` (`zona` ASC) VISIBLE,
  CONSTRAINT `Zona`
    FOREIGN KEY (`zona`)
    REFERENCES `mydb`.`ZONA` (`nombre_zona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`CONSTRUCCION`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`CONSTRUCCION` (
  `calle` VARCHAR(45) NOT NULL,
  `numero` INT NOT NULL,
  `coordenadas` VARCHAR(45) NOT NULL,
  `año_construccion` INT NULL,
  `superficie` INT NULL,
  PRIMARY KEY (`calle`, `numero`, `coordenadas`),
  INDEX `calle_idx` (`calle` ASC) VISIBLE,
  CONSTRAINT `calle`
    FOREIGN KEY (`calle`)
    REFERENCES `mydb`.`CALLE` (`nombre_calle`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`BLOQUE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`BLOQUE` (
  `calle` VARCHAR(45) NOT NULL,
  `numero` INT NOT NULL,
  `coordenadas` VARCHAR(45) NOT NULL,
  `numero_pisos` INT NULL,
  `numero_ascensores` INT NULL,
  `superficie` INT NULL,
  PRIMARY KEY (`calle`, `numero`, `coordenadas`),
  CONSTRAINT `numero`
    FOREIGN KEY (`numero`)
    REFERENCES `mydb`.`CONSTRUCCION` (`numero`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `coordenadas`
    FOREIGN KEY (`coordenadas`)
    REFERENCES `mydb`.`CONSTRUCCION` (`coordenadas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `calle`
    FOREIGN KEY (`calle`)
    REFERENCES `mydb`.`CONSTRUCCION` (`calle`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`PISO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`PISO` (
  `calle` VARCHAR(45) NOT NULL,
  `numero` INT NOT NULL,
  `planta` VARCHAR(45) NOT NULL,
  `letra` VARCHAR(45) NOT NULL,
  `superficie` INT NULL,
  `numero_habitantes` INT NULL,
  `dueño` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`calle`, `numero`, `planta`, `letra`),
  INDEX `numero_idx` (`numero` ASC) VISIBLE,
  INDEX `calle_idx` (`calle` ASC) VISIBLE,
  INDEX `dueño_idx` (`dueño` ASC) VISIBLE,
  CONSTRAINT `numero`
    FOREIGN KEY (`numero`)
    REFERENCES `mydb`.`BLOQUE` (`numero`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `calle`
    FOREIGN KEY (`calle`)
    REFERENCES `mydb`.`BLOQUE` (`calle`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `dueño`
    FOREIGN KEY (`dueño`)
    REFERENCES `mydb`.`PERSONA` (`dni`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`VIVIENDA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`VIVIENDA` (
  `calle` VARCHAR(45) NOT NULL,
  `numero` INT NOT NULL,
  `coordenadas` VARCHAR(45) NOT NULL,
  `superficie` INT NULL,
  `numero_habitantes` INT NULL,
  `eficiencia` VARCHAR(45) NULL,
  `dueño` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`calle`, `numero`, `coordenadas`),
  INDEX `dueño_idx` (`dueño` ASC) VISIBLE,
  INDEX `coordenadas_idx` (`coordenadas` ASC) VISIBLE,
  CONSTRAINT `numero`
    FOREIGN KEY (`numero`)
    REFERENCES `mydb`.`CONSTRUCCION` (`numero`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `coordenadas`
    FOREIGN KEY (`coordenadas`)
    REFERENCES `mydb`.`CONSTRUCCION` (`coordenadas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `calle`
    FOREIGN KEY (`calle`)
    REFERENCES `mydb`.`CONSTRUCCION` (`calle`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `dueño`
    FOREIGN KEY (`dueño`)
    REFERENCES `mydb`.`PERSONA` (`dni`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`PERSONA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`PERSONA` (
  `dni` VARCHAR(45) NOT NULL,
  `nombre` VARCHAR(45) NULL,
  `fecha_nacimiento` VARCHAR(45) NULL,
  `persona_cabeza` VARCHAR(45) NOT NULL,
  `calle` VARCHAR(45) NULL,
  `numero` INT NULL,
  `letra` VARCHAR(45) NULL,
  `planta` VARCHAR(45) NULL,
  INDEX `persona_cabeza_idx` (`persona_cabeza` ASC) VISIBLE,
  INDEX `direccion_piso_idx` (`calle` ASC, `numero` ASC, `letra` ASC, `planta` ASC) VISIBLE,
  PRIMARY KEY (`dni`),
  CONSTRAINT `persona_cabeza`
    FOREIGN KEY (`persona_cabeza`)
    REFERENCES `mydb`.`PERSONA` (`dni`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `direccion_piso`
    FOREIGN KEY (`calle` , `numero` , `letra` , `planta`)
    REFERENCES `mydb`.`PISO` (`calle` , `numero` , `letra` , `planta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `dirrecion_vivienda`
    FOREIGN KEY (`calle` , `numero`)
    REFERENCES `mydb`.`VIVIENDA` (`calle` , `numero`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
