-- MySQL Script generated by MySQL Workbench
-- Fri Nov 13 20:08:08 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema viveros
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema viveros
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `viveros` DEFAULT CHARACTER SET utf8 ;
USE `viveros` ;

-- -----------------------------------------------------
-- Table `viveros`.`VIVERO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `viveros`.`VIVERO` (
  `ubicacion` VARCHAR(45) NOT NULL,
  `nombre` VARCHAR(45) NULL,
  `hora_apertura` VARCHAR(45) NULL,
  `hora_cierre` VARCHAR(45) NULL,
  PRIMARY KEY (`ubicacion`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `viveros`.`ZONAS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `viveros`.`ZONAS` (
  `nombre_zona` VARCHAR(45) NOT NULL,
  `vivero` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`nombre_zona`, `vivero`),
  INDEX `vivero_idx` (`vivero` ASC) VISIBLE,
  CONSTRAINT `vivero`
    FOREIGN KEY (`vivero`)
    REFERENCES `viveros`.`VIVERO` (`ubicacion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `viveros`.`PRODUCTO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `viveros`.`PRODUCTO` (
  `cod_barras` INT NOT NULL,
  `precio` DECIMAL NULL,
  `stock` INT NULL,
  `tipo` VARCHAR(45) NULL,
  `caducidad` VARCHAR(45) NULL,
  `nombre` VARCHAR(45) NULL,
  PRIMARY KEY (`cod_barras`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `viveros`.`CLIENTE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `viveros`.`CLIENTE` (
  `dni` VARCHAR(45) NOT NULL,
  `num_cliente` INT NOT NULL,
  `num_tarjeta` VARCHAR(45) NULL,
  `gasto_mensual` DECIMAL NULL,
  `bonificacion` INT NULL,
  PRIMARY KEY (`dni`, `num_cliente`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `viveros`.`EMPLEADO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `viveros`.`EMPLEADO` (
  `dni` VARCHAR(45) NOT NULL,
  `tarjeta_ss` VARCHAR(45) NOT NULL,
  `nombre` VARCHAR(45) NULL,
  `horario` VARCHAR(45) NULL,
  PRIMARY KEY (`dni`, `tarjeta_ss`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `viveros`.`PEDIDO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `viveros`.`PEDIDO` (
  `num_pedido` INT NOT NULL,
  `fecha` VARCHAR(45) NULL,
  `importe` DECIMAL NULL,
  `cliente` INT NULL,
  `empleado` VARCHAR(45) NULL,
  `producto` INT NULL,
  PRIMARY KEY (`num_pedido`),
  INDEX `cliente_idx` (`cliente` ASC) VISIBLE,
  INDEX `empleado_idx` (`empleado` ASC) VISIBLE,
  CONSTRAINT `cliente`
    FOREIGN KEY (`cliente`)
    REFERENCES `viveros`.`CLIENTE` (`num_cliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `empleado`
    FOREIGN KEY (`empleado`)
    REFERENCES `viveros`.`EMPLEADO` (`dni`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `viveros`.`PEDIDO_has_PRODUCTO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `viveros`.`PEDIDO_has_PRODUCTO` (
  `PRODUCTO_cod_barras` INT NOT NULL,
  `PEDIDO_num_pedido` INT NOT NULL,
  PRIMARY KEY (`PRODUCTO_cod_barras`, `PEDIDO_num_pedido`),
  INDEX `fk_PRODUCTO_has_PEDIDO_PEDIDO1_idx` (`PEDIDO_num_pedido` ASC) VISIBLE,
  INDEX `fk_PRODUCTO_has_PEDIDO_PRODUCTO1_idx` (`PRODUCTO_cod_barras` ASC) VISIBLE,
  CONSTRAINT `fk_PRODUCTO_has_PEDIDO_PRODUCTO1`
    FOREIGN KEY (`PRODUCTO_cod_barras`)
    REFERENCES `viveros`.`PRODUCTO` (`cod_barras`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_PRODUCTO_has_PEDIDO_PEDIDO1`
    FOREIGN KEY (`PEDIDO_num_pedido`)
    REFERENCES `viveros`.`PEDIDO` (`num_pedido`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `viveros`.`ZONAS_has_PRODUCTO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `viveros`.`ZONAS_has_PRODUCTO` (
  `PRODUCTO_cod_barras` INT NOT NULL,
  `ZONAS_nombre_zona` VARCHAR(45) NOT NULL,
  `ZONAS_vivero` VARCHAR(45) NOT NULL,
  `stock` VARCHAR(45) NULL,
  PRIMARY KEY (`PRODUCTO_cod_barras`, `ZONAS_nombre_zona`, `ZONAS_vivero`),
  INDEX `fk_PRODUCTO_has_ZONAS_ZONAS1_idx` (`ZONAS_nombre_zona` ASC, `ZONAS_vivero` ASC) VISIBLE,
  INDEX `fk_PRODUCTO_has_ZONAS_PRODUCTO1_idx` (`PRODUCTO_cod_barras` ASC) VISIBLE,
  CONSTRAINT `fk_PRODUCTO_has_ZONAS_PRODUCTO1`
    FOREIGN KEY (`PRODUCTO_cod_barras`)
    REFERENCES `viveros`.`PRODUCTO` (`cod_barras`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_PRODUCTO_has_ZONAS_ZONAS1`
    FOREIGN KEY (`ZONAS_nombre_zona` , `ZONAS_vivero`)
    REFERENCES `viveros`.`ZONAS` (`nombre_zona` , `vivero`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `viveros`.`ZONAS_has_EMPLEADO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `viveros`.`ZONAS_has_EMPLEADO` (
  `ZONAS_nombre_zona` VARCHAR(45) NOT NULL,
  `ZONAS_vivero` VARCHAR(45) NOT NULL,
  `EMPLEADO_dni` VARCHAR(45) NOT NULL,
  `EMPLEADO_tarjeta_ss` VARCHAR(45) NOT NULL,
  `fecha_inicio` VARCHAR(45) NULL,
  `fecha_fin` VARCHAR(45) NULL,
  PRIMARY KEY (`ZONAS_nombre_zona`, `ZONAS_vivero`, `EMPLEADO_dni`, `EMPLEADO_tarjeta_ss`),
  INDEX `fk_ZONAS_has_EMPLEADO_EMPLEADO1_idx` (`EMPLEADO_dni` ASC, `EMPLEADO_tarjeta_ss` ASC) VISIBLE,
  INDEX `fk_ZONAS_has_EMPLEADO_ZONAS1_idx` (`ZONAS_nombre_zona` ASC, `ZONAS_vivero` ASC) VISIBLE,
  CONSTRAINT `fk_ZONAS_has_EMPLEADO_ZONAS1`
    FOREIGN KEY (`ZONAS_nombre_zona` , `ZONAS_vivero`)
    REFERENCES `viveros`.`ZONAS` (`nombre_zona` , `vivero`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ZONAS_has_EMPLEADO_EMPLEADO1`
    FOREIGN KEY (`EMPLEADO_dni` , `EMPLEADO_tarjeta_ss`)
    REFERENCES `viveros`.`EMPLEADO` (`dni` , `tarjeta_ss`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
