-- MySQL Script generated by MySQL Workbench
-- Sun Nov 22 23:38:07 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema catastro
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema catastro
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `catastro` DEFAULT CHARACTER SET utf8 ;
USE `catastro` ;

-- -----------------------------------------------------
-- Table `catastro`.`ZONA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `catastro`.`ZONA` (
  `nombre_zona` VARCHAR(45) NOT NULL,
  `area` DECIMAL NULL,
  `concejal_responsable` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`nombre_zona`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `catastro`.`CALLE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `catastro`.`CALLE` (
  `calle` VARCHAR(45) NOT NULL,
  `tipo` VARCHAR(45) NULL,
  `numero_contenedores` INT NULL,
  `nombre_zona` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`calle`),
  INDEX `fk_CALLE_ZONA1_idx` (`nombre_zona` ASC),
  CONSTRAINT `fk_CALLE_ZONA1`
    FOREIGN KEY (`nombre_zona`)
    REFERENCES `catastro`.`ZONA` (`nombre_zona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `catastro`.`CONSTRUCCION`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `catastro`.`CONSTRUCCION` (
  `fecha_construccion` VARCHAR(45) NULL,
  `superficie` INT NULL,
  `calle` VARCHAR(45) NOT NULL,
  `numero` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`calle`, `numero`),
  INDEX `fk_CONSTRUCCION_CALLE1_idx` (`calle` ASC),
  CONSTRAINT `fk_CONSTRUCCION_CALLE1`
    FOREIGN KEY (`calle`)
    REFERENCES `catastro`.`CALLE` (`calle`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `catastro`.`BLOQUE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `catastro`.`BLOQUE` (
  `numero_pisos` INT NULL,
  `numero_ascensores` INT NULL,
  `superficie` INT NULL,
  `numero` INT NOT NULL,
  `calle` VARCHAR(45) NOT NULL,
  `nombre_zona` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`numero`, `calle`, `nombre_zona`),
  INDEX `fk_BLOQUE_CONSTRUCCION1_idx` (`calle` ASC, `nombre_zona` ASC),
  CONSTRAINT `fk_BLOQUE_CONSTRUCCION1`
    FOREIGN KEY (`calle`)
    REFERENCES `catastro`.`CONSTRUCCION` (`calle`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `catastro`.`PISO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `catastro`.`PISO` (
  `planta` INT NOT NULL,
  `letra` VARCHAR(45) NOT NULL,
  `superficie` INT NULL,
  `numero_habitantes` INT NULL,
  `numero` INT NOT NULL,
  `calle` VARCHAR(45) NOT NULL,
  `propietario` VARCHAR(45) NULL,
  PRIMARY KEY (`planta`, `letra`, `numero`, `calle`),
  INDEX `fk_PISO_BLOQUE1_idx` (`numero` ASC, `calle` ASC),
  INDEX `fk_PISO_PERSONA1_idx` (`propietario` ASC),
  CONSTRAINT `fk_PISO_BLOQUE1`
    FOREIGN KEY (`numero` , `calle`)
    REFERENCES `catastro`.`BLOQUE` (`numero` , `calle`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_PISO_PERSONA1`
    FOREIGN KEY (`propietario`)
    REFERENCES `catastro`.`PERSONA` (`dni`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `catastro`.`VIVIENDA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `catastro`.`VIVIENDA` (
  `superficie` INT NULL,
  `numero_habitantes` INT NULL,
  `eficiencia` VARCHAR(45) NULL,
  `numero` INT NOT NULL,
  `calle` VARCHAR(45) NOT NULL,
  `propietario` VARCHAR(45) NULL,
  PRIMARY KEY (`numero`, `calle`),
  INDEX `fk_VIVIENDA_CONSTRUCCION1_idx` (`calle` ASC),
  INDEX `fk_VIVIENDA_PERSONA2_idx` (`propietario` ASC),
  CONSTRAINT `fk_VIVIENDA_CONSTRUCCION1`
    FOREIGN KEY (`calle`)
    REFERENCES `catastro`.`CONSTRUCCION` (`calle`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_VIVIENDA_PERSONA2`
    FOREIGN KEY (`propietario`)
    REFERENCES `catastro`.`PERSONA` (`dni`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `catastro`.`PERSONA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `catastro`.`PERSONA` (
  `dni` VARCHAR(45) NOT NULL,
  `nombre` VARCHAR(45) NULL,
  `fecha_nacimiento` VARCHAR(45) NULL,
  `cabeza_dni` VARCHAR(45) NULL,
  `PISO_planta` INT NULL,
  `PISO_letra` VARCHAR(45) NULL,
  `PISO_numero` INT NULL,
  `PISO_calle` VARCHAR(45) NULL,
  `VIVIENDA_numero` INT NULL,
  `VIVIENDA_calle` VARCHAR(45) NULL,
  PRIMARY KEY (`dni`),
  INDEX `fk_PERSONA_PERSONA1_idx` (`cabeza_dni` ASC),
  INDEX `fk_PERSONA_PISO1_idx` (`PISO_planta` ASC, `PISO_letra` ASC, `PISO_numero` ASC, `PISO_calle` ASC),
  INDEX `fk_PERSONA_VIVIENDA1_idx` (`VIVIENDA_numero` ASC, `VIVIENDA_calle` ASC),
  CONSTRAINT `fk_PERSONA_PERSONA1`
    FOREIGN KEY (`cabeza_dni`)
    REFERENCES `catastro`.`PERSONA` (`dni`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_PERSONA_PISO1`
    FOREIGN KEY (`PISO_planta` , `PISO_letra` , `PISO_numero` , `PISO_calle`)
    REFERENCES `catastro`.`PISO` (`planta` , `letra` , `numero` , `calle`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_PERSONA_VIVIENDA1`
    FOREIGN KEY (`VIVIENDA_numero` , `VIVIENDA_calle`)
    REFERENCES `catastro`.`VIVIENDA` (`numero` , `calle`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

USE `catastro`;

DELIMITER $$
USE `catastro`$$
CREATE DEFINER = CURRENT_USER TRIGGER `catastro`.`PERSONA_BEFORE_INSERT` BEFORE INSERT ON `PERSONA` FOR EACH ROW
BEGIN
IF NEW.PISO_numero IS NOT NULL AND NEW.VIVIENDA_numero IS NOT NULL THEN
		SIGNAL SQLSTATE '02000' SET MESSAGE_TEXT = 'Una persona no puede estar en dos viviendas';
	END IF;

END$$

USE `catastro`$$
CREATE DEFINER = CURRENT_USER TRIGGER `catastro`.`PERSONA_BEFORE_UPDATE` BEFORE UPDATE ON `PERSONA` FOR EACH ROW
BEGIN
IF NEW.PISO_numero IS NOT NULL AND NEW.VIVIENDA_numero IS NOT NULL THEN
		SIGNAL SQLSTATE '02000' SET MESSAGE_TEXT = 'Una persona no puede estar en dos viviendas';
	END IF;
END$$


DELIMITER ;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `catastro`.`ZONA`
-- -----------------------------------------------------
START TRANSACTION;
USE `catastro`;
INSERT INTO `catastro`.`ZONA` (`nombre_zona`, `area`, `concejal_responsable`) VALUES ('La Cuesta', 14500, 'Ana García');
INSERT INTO `catastro`.`ZONA` (`nombre_zona`, `area`, `concejal_responsable`) VALUES ('La Laguna ', 50000, 'Juan Gil');

COMMIT;


-- -----------------------------------------------------
-- Data for table `catastro`.`CALLE`
-- -----------------------------------------------------
START TRANSACTION;
USE `catastro`;
INSERT INTO `catastro`.`CALLE` (`calle`, `tipo`, `numero_contenedores`, `nombre_zona`) VALUES ('San Juan', 'Avenida', 4, 'La Cuesta');
INSERT INTO `catastro`.`CALLE` (`calle`, `tipo`, `numero_contenedores`, `nombre_zona`) VALUES ('San Agustín', 'Calleja', 1, 'La Laguna');

COMMIT;


-- -----------------------------------------------------
-- Data for table `catastro`.`CONSTRUCCION`
-- -----------------------------------------------------
START TRANSACTION;
USE `catastro`;
INSERT INTO `catastro`.`CONSTRUCCION` (`fecha_construccion`, `superficie`, `calle`, `numero`) VALUES ('1985', 120, 'San Agustín', '1');
INSERT INTO `catastro`.`CONSTRUCCION` (`fecha_construccion`, `superficie`, `calle`, `numero`) VALUES ('2010', 400, 'San Juan', '12');

COMMIT;


-- -----------------------------------------------------
-- Data for table `catastro`.`BLOQUE`
-- -----------------------------------------------------
START TRANSACTION;
USE `catastro`;
INSERT INTO `catastro`.`BLOQUE` (`numero_pisos`, `numero_ascensores`, `superficie`, `numero`, `calle`, `nombre_zona`) VALUES (4, 3, 120, 12, 'San Juan', 'La Cuesta');

COMMIT;


-- -----------------------------------------------------
-- Data for table `catastro`.`PISO`
-- -----------------------------------------------------
START TRANSACTION;
USE `catastro`;
INSERT INTO `catastro`.`PISO` (`planta`, `letra`, `superficie`, `numero_habitantes`, `numero`, `calle`, `propietario`) VALUES (3, 'A', 120, 1, 12, 'San Juan', NULL);

COMMIT;


-- -----------------------------------------------------
-- Data for table `catastro`.`VIVIENDA`
-- -----------------------------------------------------
START TRANSACTION;
USE `catastro`;
INSERT INTO `catastro`.`VIVIENDA` (`superficie`, `numero_habitantes`, `eficiencia`, `numero`, `calle`, `propietario`) VALUES (200, 2, 'A', 1, 'San Agustín', NULL);

COMMIT;


-- -----------------------------------------------------
-- Data for table `catastro`.`PERSONA`
-- -----------------------------------------------------
START TRANSACTION;
USE `catastro`;
INSERT INTO `catastro`.`PERSONA` (`dni`, `nombre`, `fecha_nacimiento`, `cabeza_dni`, `PISO_planta`, `PISO_letra`, `PISO_numero`, `PISO_calle`, `VIVIENDA_numero`, `VIVIENDA_calle`) VALUES ('1111', 'Ana García', '1975', '1111', NULL, NULL, NULL, NULL, 1, 'San Agustín');
INSERT INTO `catastro`.`PERSONA` (`dni`, `nombre`, `fecha_nacimiento`, `cabeza_dni`, `PISO_planta`, `PISO_letra`, `PISO_numero`, `PISO_calle`, `VIVIENDA_numero`, `VIVIENDA_calle`) VALUES ('2222', 'Pedro Coello', '1945', '2222', 3, 'A', 12, 'San Juan', NULL, NULL);

COMMIT;

